---
title: "PovcalNet API Query Builder"
author: "Ratnadeep Mitra"
date: "September 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# required packages
```

```{r}
QueryBuilder <- function(poverty_line,
                         year_selected,
                         countries,
                         year_list,
                         poverty_line_list,
                         country_list) {
  
  url <- "http://iResearch.worldbank.org/PovcalNet/PovcalNetAPI.ashx?"
  query_string <- ""
  err_flag <- FALSE
  
  tryCatch({
    
    # check if all required parameters are supplied
    # not sure if I need to do this
    # will need to check the error handling that is already implemented in the C# code
    if (is.na(poverty_line) || poverty_line == ''){
      if (is.na(year_selected) || year_selected == ''){
        if (is.na(countries) || countries == ''){
          if (is.na(poverty_line_list) || poverty_line_list == ''){
            print("Poverty Line is required")
            err_flag = TRUE
          }
          if (is.na(country_list) || country_list == ''){
            print("Country is required")
            err_flag = TRUE
          }
        }
      }
    }
    
    if (err_flag == TRUE) {
      stop("Execution stopped")
    }
    
    # split comma-separated strings into vectors
    else if (err_flag == FALSE) {
      
      if (!is.na(poverty_line) || !poverty_line == ''){
        query_string <- query_string + "poverty_line=" + poverty_line + "&"
      }
      else {
        if (!is.na(poverty_line_list) || !poverty_line_list == '') {
          PL <- unlist(strsplit(poverty_line_list, split = ","))
        }
      }
      
      if (!is.na(countries) || !countries == ''){
        query_string <- query_string + "countries=" + countries + "&"
      }
      else {
        if (!is.na(country_list) || !country_list == '') {
          C <- unlist(strsplit(country_list, split = ","))
        }
      }
      
      if (!is.na(year_selected) || !year_selected == ''){
        query_string <- query_string + "year_selected=" + year_selected + "&"
      }
      else {
        if (!is.na(year_list) || !year_list == '') {
          Y <- unlist(strsplit(year_list, split = "&"))
        }
      }
      
    }
    
    # loop through vectors, get each element and build query string
    # to be implemented
    
  }, error = function(err){
    stop("Execution stopped")
  })
  
}
```

```{r}
QueryBuilder(poverty_line = '',
            year_selected = '',
            countries = '',
            year_list = '2008',
            poverty_line_list = '1.9',
            country_list = 'IND')
```

